apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-app-ds
  labels:
    app: frontend-ds
    type: development
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable
