apiVersion: v1
kind: Pod
metadata:
  name: init-con-pod
spec:
  containers:
  - name: main-con
    image: nginx:stable
  initContainers:
  - name:  init-con-pod
    image: busybox:stable
    command: ['sh', '-c', 'sleep 20']
