apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: demo-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      limits:
        cpu: 0.5
      requests:
        cpu: 0.25
 
