apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
  - name: nginx
    image: kodekloud/webapp-color
    args:
    - --color
    - blue
    ports:
    - containerPort: 80
