apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      containers:
      - name: nginx
        image: kodekloud/simple-webapp:red
        ports:
        - containerPort: 8080
