apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: password123
    image: mysql/mysql-server:8.0
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
      
